version: "3.7"

services:
  database:
    image: postgres
    container_name: database_rentalx
    restart: always
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: rentx
      POSTGRES_DB: rentalx
    volumes:
      - pgdata:/data/postgres

  app: 
    build: .
    container_name: rentalx
    links:
      - database
    depends_on: 
      - database
    ports:
      - 3333:3333
    volumes:
      - .:/usr/ap

volumes:
  pgdata: 
    driver: local